version: "2"
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:6.0.0
    ports:
      - 8080:8080
    user: root
    volumes:
      - logstash-conf:/usr/share/logstash/pipeline
      - logstash-data:/usr/share/logstash/data/queue
    environment:
      - XPACK_MONITORING_ENABLED=false
      - CONFIG_RELOAD_AUTOMATIC=true
      - QUEUE_TYPE=persisted
      
  consul:
    image: consul:1.0.0
    ports:
      - 8500:8500
    volumes:
      - consul-data:/consul/data

  reloader:
    build: .
    image: diogok/logstash-http-output-reloader
    volumes:
      - logstash-conf:/opt/config

volumes:
  logstash-conf:
  logstash-data:
  consul-data:
